
version: '3.8'

services:

  mc:

    image: itzg/minecraft-server

    container_name: forge-mc

    ports:

      - "25565:25565"

    environment:

      EULA: "TRUE"

      TYPE: FORGE

      VERSION: "1.21.5"

      FORGEVERSION: "55.0.16"

    volumes:

      - ./data:/data

    restart: unless-stopped